import Header from '@/components/Header'
import '../styles/globals.css'
import PromptInput from '@/components/PromptInput'
import ClientProvider from "../components/ClientProvider";
export const metadata = {
  title: 'DK AI Art Gallery',
  description: 'Generated by DK',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body>
        <ClientProvider>
          {/* Header */}
          <Header />

          {/* Prompt Input */}
          <PromptInput />
          {children}
        </ClientProvider>

      </body>
    </html>
  )
}
